package com.lhb.kiotviet_quanly.view.navigation

enum class ScreenName(val route: String) {
    OnBoardingScreen("OnBoardingScreen"),
    WelcomeScreen("WelcomeScreen"),
    SignUpScreen("SignUpScreen"),
    SignInScreen("SignInScreen"),
    BottomTav("bottomTav"),
    ForgotPasswordScreen("ForgotPasswordScreen"),
    CancelExportScreen("CancelExportScreen"),
    CheckInventoryScreen("CheckInventoryScreen"),
    OrderScreen("OrderScreen"),
    ReturnGoodsScreen("ReturnGoodsScreen"),
    ReturnImportedGoodsScreen("ReturnImportedGoodsScreen"),
    ProductDetailScreen("ProductDetailScreen"),
    UpdateOtherInformationScreen("UpdateOtherInformationScreen"),
    TrademarkScreen("TrademarkScreen"),
    NewTrademarkScreen("NewTrademarkScreen"),
    AddressScreen("AddressScreen"),
    NewAddressScreen("NewAddressScreen"),
    AddDescription("AddDescription"),
    WarehouseCardScreen("WarehouseCardScreen"),
    InventoryLevels("InventoryLevels"),
    OrderDetailScreen("OrderDetailScreen"),
    ProductOrderDetailScreen("ProductOrderDetailScreen"),
    RetailCustomersScreen("RetailCustomersScreen"),
    PaymentMethodScreen("PaymentMethodScreen"),
    AddProductScreen("AddProductScreen"),
}